// scan-wolf.cc generated by reflex 3.3.0 from scan-wolf.ll

#define REFLEX_VERSION "3.3.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_debug
#undef REFLEX_OPTION_flex
#undef REFLEX_OPTION_header_file
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_noyywrap
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_params
#undef REFLEX_OPTION_prefix

#define REFLEX_OPTION_debug               true
#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_header_file         "scan-wolf.hh"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           lexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "scan-wolf.cc"
#define REFLEX_OPTION_params              driver::WolfDriver& wd, std::queue<lexer::Token>& tokens
#define REFLEX_OPTION_prefix              yy

// --debug option enables ASSERT:
#define ASSERT(c) assert(c)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 12 "scan-wolf.ll"


#define YY_EXTERN_C extern "C" // For linkage rule

#include <queue>
#include <cerrno>
#include <climits>
#include <regex>
#include <string>

#include "token.hh"
#include "../driver/wolf-driver.hh"
#include "../misc/location.hh"

	/* (Define YY_USER_ACTION to update locations). */
#define YY_USER_ACTION col += size();

#define GET_LOC Location{file, line, col, col + yyleng - 1}
#define GET_TOK(Type) Type ## _TOK

#define TOKEN(Type)										\
	token_type type = Type ## _TOK;						\
	misc::Location location{file, line, col - YYLeng() + 1, col};	\
	Token token{type, location};						\
	tokens.emplace(token);

#define TOKEN_VAL(Type, Value)										\
	token_type type = Type ## _TOK;									\
	misc::Location location{file, line, col - YYLeng() + 1, col};	\
	Token token{type, location, Value};						\
	tokens.emplace(token);




////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE DEFINITIONS                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define INITIAL (0)
#define SC_COMMENT (1)
#define SC_NEW_LOC (2)
#define YY_NUM_RULES (101)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>

namespace lexer {

typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;

} // namespace lexer

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace lexer {

class Lexer : public FlexLexer {
#line 48 "scan-wolf.ll"

	std::string file;
	unsigned line;
	unsigned col;

	// Use to got new location
	std::string new_file;
	int new_line;

	// Use to detect subcomment
	unsigned lvl;

 public:
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
#line 61 "scan-wolf.ll"

	file = "";
	line = 0;
	col = 0;

	new_file = "";
	new_line = 0;

	lvl = 0;

    set_debug(true);
  }
  virtual int yylex(void)
  {
    LexerError("Lexer::yylex invoked but %option lex=lex is used");
    yyterminate();
  }
  // the flex lexer function defined by SECTION 2
  virtual int lex(driver::WolfDriver& wd, std::queue<lexer::Token>& tokens);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input, driver::WolfDriver& wd, std::queue<lexer::Token>& tokens)
  {
    in(input);
    return lex(wd, tokens);
  }
  int lex(const reflex::Input& input, std::ostream *os, driver::WolfDriver& wd, std::queue<lexer::Token>& tokens)
  {
    in(input);
    if (os)
      out(*os);
    return lex(wd, tokens);
  }
};

} // namespace lexer

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "scan-wolf.ll"
/* -*- C++ -*- */
// %option defines the parameters with which the flex will be launched
#line 6 "scan-wolf.ll"
// Add a param of function lex() generate in Lexer class
#line 9 "scan-wolf.ll"
// Name of the class generate by flex
#line 72 "scan-wolf.ll"
/* Abbreviations.  */

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int lexer::Lexer::lex(driver::WolfDriver& wd, std::queue<lexer::Token>& tokens)
{
  static const char *REGEX_INITIAL = "(?m)((?:\\Q/*\\E))|((?:\\Q# \\E))|((?:[\\x09\\x0b\\x0c\\x20]))|(\\n\\r)|(\\r\\n)|(\\n)|(\\r)|((?:\\Qauto\\b\\E))|((?:\\Qvoid\\b\\E))|((?:\\Qint\\b\\E))|((?:\\Qchar\\b\\E))|((?:\\Qflot\\b\\E))|((?:\\Qdouble\\b\\E))|((?:\\Qunsigned\\b\\E))|((?:\\Qsigned\\b\\E))|((?:\\Qlong\\b\\E))|((?:\\Qshort\\b\\E))|((?:\\Qregister\\b\\E))|((?:\\Qstruct\\b\\E))|((?:\\Qunion\\b\\E))|((?:\\Qenum\\b\\E))|((?:\\Qtypedef\\b\\E))|((?:\\Qextern\\b\\E))|((?:\\Qconst\\b\\E))|((?:\\Qstatic\\b\\E))|((?:\\Qinline\\b\\E))|((?:\\Qvolatile\\b\\E))|((?:\\Qwhile\\b\\E))|((?:\\Qfor\\b\\E))|((?:\\Qdo\\b\\E))|((?:\\Qbreak\\b\\E))|((?:\\Qcontinue\\b\\E))|((?:\\Qif\\b\\E))|((?:\\Qelse\\b\\E))|((?:\\Qswitch\\b\\E))|((?:\\Qcase\\b\\E))|((?:\\Qdefault\\b\\E))|((?:\\Qgoto\\b\\E))|((?:\\Qsizeof\\b\\E))|((?:\\Qreturn\\b\\E))|((?:\\Q==\\E))|((?:\\Q!=\\E))|((?:\\Q&&\\E))|((?:\\Q||\\E))|((?:\\Q>=\\E))|((?:\\Q<=\\E))|((?:\\Q>\\E))|((?:\\Q<\\E))|((?:\\Q!\\E))|((?:\\Q+\\E))|((?:\\Q-\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q%\\E))|((?:\\Q~\\E))|((?:\\Q&\\E))|((?:\\Q|\\E))|((?:\\Q^\\E))|((?:\\Q>>\\E))|((?:\\Q<<\\E))|((?:\\Q?\\E))|((?:\\Q++\\E))|((?:\\Q--\\E))|((?:\\Q+=\\E))|((?:\\Q-=\\E))|((?:\\Q*=\\E))|((?:\\Q/=\\E))|((?:\\Q%=\\E))|((?:\\Q&=\\E))|((?:\\Q|=\\E))|((?:\\Q^=\\E))|((?:\\Q>>=\\E))|((?:\\Q<<=\\E))|((?:\\Q=\\E))|((?:\\Q.\\E))|((?:\\Q->\\E))|((?:\\Q,\\E))|((?:\\Q;\\E))|((?:\\Q:\\E))|((?:\\Q...\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|((?:\\Q{\\E)|(?:\\Q<%\\E))|((?:\\Q}\\E)|(?:\\Q%>\\E))|((?:\\Q[\\E)|(?:\\Q<:\\E))|((?:\\Q]\\E)|(?:\\Q:>\\E))|((?:[0-9]+\\b))|((?:(?:\\Q\"\\E).*(?:\\Q\"\\E)))|((?:[A-Z_a-z][0-9A-Z_a-z]*\\b))|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  static const char *REGEX_SC_COMMENT = "(?m)((?:\\Q/*\\E))|((?:\\Q*/\\E))|(.|\\n)";
  static const reflex::Pattern PATTERN_SC_COMMENT(REGEX_SC_COMMENT);
  static const char *REGEX_SC_NEW_LOC = "(?m)((?:[0-9]+\\b))|((?:(?:\\Q\"\\E).*(?:\\Q\"\\E)))|(.)|(\\n)";
  static const reflex::Pattern PATTERN_SC_NEW_LOC(REGEX_SC_NEW_LOC);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
  while (true)
  {
    switch (start())
    {
      case INITIAL:
        matcher().pattern(PATTERN_INITIAL);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              if (debug()) std::cerr << "--\033[1;35mEOF rule scan-wolf.ll:237\033[0m start(" << start() << ")\n";
#line 237 "scan-wolf.ll"
{ TOKEN(END_OF_FILE); return 0; }

            }
            else
            {
              if (debug()) std::cerr << "--\033[1;31mdefault rule\033[0m\n";
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule scan-wolf.ll:130: "/*" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:130\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 130 "scan-wolf.ll"
{ lvl = 1; start(SC_COMMENT); }

            YY_BREAK
          case 2: // rule scan-wolf.ll:132: "# " :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:132\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 132 "scan-wolf.ll"
{
	new_line = -1;
	start(SC_NEW_LOC);
}

            YY_BREAK
          case 3: // rule scan-wolf.ll:137: {BLANK} :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:137\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 137 "scan-wolf.ll"
{ /* DO nothing */ }

            YY_BREAK
          case 4: // rule scan-wolf.ll:139: \n\r :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:139\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 139 "scan-wolf.ll"
{ line++; col = 0; }
            YY_BREAK
          case 5: // rule scan-wolf.ll:140: \r\n :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:140\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 140 "scan-wolf.ll"
{ line++; col = 0; }
            YY_BREAK
          case 6: // rule scan-wolf.ll:141: \n :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:141\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 141 "scan-wolf.ll"
{ line++; col = 0; }
            YY_BREAK
          case 7: // rule scan-wolf.ll:142: \r :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:142\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 142 "scan-wolf.ll"
{ line++; col = 0; }

            YY_BREAK
          case 8: // rule scan-wolf.ll:144: "auto\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:144\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 144 "scan-wolf.ll"
{ /* keyword auto is ignored */ }

            YY_BREAK
          case 9: // rule scan-wolf.ll:146: "void\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:146\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 146 "scan-wolf.ll"
{ TOKEN(VOID); }
            YY_BREAK
          case 10: // rule scan-wolf.ll:147: "int\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:147\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 147 "scan-wolf.ll"
{ TOKEN(INT); }
            YY_BREAK
          case 11: // rule scan-wolf.ll:148: "char\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:148\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 148 "scan-wolf.ll"
{ TOKEN(CHAR); }
            YY_BREAK
          case 12: // rule scan-wolf.ll:149: "flot\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:149\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 149 "scan-wolf.ll"
{ TOKEN(FLOAT); }
            YY_BREAK
          case 13: // rule scan-wolf.ll:150: "double\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:150\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 150 "scan-wolf.ll"
{ TOKEN(DOUBLE); }
            YY_BREAK
          case 14: // rule scan-wolf.ll:151: "unsigned\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:151\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 151 "scan-wolf.ll"
{ TOKEN(UNSIGNED); }
            YY_BREAK
          case 15: // rule scan-wolf.ll:152: "signed\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:152\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 152 "scan-wolf.ll"
{ TOKEN(SIGNED); }
            YY_BREAK
          case 16: // rule scan-wolf.ll:153: "long\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:153\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 153 "scan-wolf.ll"
{ TOKEN(LONG); }
            YY_BREAK
          case 17: // rule scan-wolf.ll:154: "short\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:154\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 154 "scan-wolf.ll"
{ TOKEN(SHORT); }
            YY_BREAK
          case 18: // rule scan-wolf.ll:155: "register\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:155\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 155 "scan-wolf.ll"
{ TOKEN(REGISTER); }

            YY_BREAK
          case 19: // rule scan-wolf.ll:157: "struct\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:157\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 157 "scan-wolf.ll"
{ TOKEN(STRUCT); }
            YY_BREAK
          case 20: // rule scan-wolf.ll:158: "union\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:158\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 158 "scan-wolf.ll"
{ TOKEN(UNION); }
            YY_BREAK
          case 21: // rule scan-wolf.ll:159: "enum\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:159\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 159 "scan-wolf.ll"
{ TOKEN(ENUM); }

            YY_BREAK
          case 22: // rule scan-wolf.ll:161: "typedef\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:161\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 161 "scan-wolf.ll"
{ TOKEN(TYPEDEF); }
            YY_BREAK
          case 23: // rule scan-wolf.ll:162: "extern\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:162\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 162 "scan-wolf.ll"
{ TOKEN(EXTERN); }
            YY_BREAK
          case 24: // rule scan-wolf.ll:163: "const\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:163\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 163 "scan-wolf.ll"
{ TOKEN(CONST); }
            YY_BREAK
          case 25: // rule scan-wolf.ll:164: "static\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:164\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 164 "scan-wolf.ll"
{ TOKEN(STATIC); }
            YY_BREAK
          case 26: // rule scan-wolf.ll:165: "inline\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:165\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 165 "scan-wolf.ll"
{ TOKEN(INLINE); }
            YY_BREAK
          case 27: // rule scan-wolf.ll:166: "volatile\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:166\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 166 "scan-wolf.ll"
{ TOKEN(VOLATILE); }

            YY_BREAK
          case 28: // rule scan-wolf.ll:168: "while\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:168\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 168 "scan-wolf.ll"
{ TOKEN(WHILE); }
            YY_BREAK
          case 29: // rule scan-wolf.ll:169: "for\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:169\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 169 "scan-wolf.ll"
{ TOKEN(FOR); }
            YY_BREAK
          case 30: // rule scan-wolf.ll:170: "do\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:170\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 170 "scan-wolf.ll"
{ TOKEN(DO); }
            YY_BREAK
          case 31: // rule scan-wolf.ll:171: "break\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:171\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 171 "scan-wolf.ll"
{ TOKEN(BREAK); }
            YY_BREAK
          case 32: // rule scan-wolf.ll:172: "continue\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:172\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 172 "scan-wolf.ll"
{ TOKEN(CONTINUE); }
            YY_BREAK
          case 33: // rule scan-wolf.ll:173: "if\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:173\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 173 "scan-wolf.ll"
{ TOKEN(IF); }
            YY_BREAK
          case 34: // rule scan-wolf.ll:174: "else\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:174\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 174 "scan-wolf.ll"
{ TOKEN(ELSE); }
            YY_BREAK
          case 35: // rule scan-wolf.ll:175: "switch\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:175\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 175 "scan-wolf.ll"
{ TOKEN(SWITCH); }
            YY_BREAK
          case 36: // rule scan-wolf.ll:176: "case\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:176\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 176 "scan-wolf.ll"
{ TOKEN(CASE); }
            YY_BREAK
          case 37: // rule scan-wolf.ll:177: "default\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:177\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 177 "scan-wolf.ll"
{ TOKEN(DEFAULT); }
            YY_BREAK
          case 38: // rule scan-wolf.ll:178: "goto\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:178\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 178 "scan-wolf.ll"
{ TOKEN(GOTO); }
            YY_BREAK
          case 39: // rule scan-wolf.ll:179: "sizeof\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:179\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 179 "scan-wolf.ll"
{ TOKEN(SIZEOF); }
            YY_BREAK
          case 40: // rule scan-wolf.ll:180: "return\b" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:180\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 180 "scan-wolf.ll"
{ TOKEN(RETURN); }

            YY_BREAK
          case 41: // rule scan-wolf.ll:182: "==" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:182\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 182 "scan-wolf.ll"
{ TOKEN(EQ); }
            YY_BREAK
          case 42: // rule scan-wolf.ll:183: "!=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:183\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 183 "scan-wolf.ll"
{ TOKEN(NOT_EQ); }
            YY_BREAK
          case 43: // rule scan-wolf.ll:184: "&&" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:184\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 184 "scan-wolf.ll"
{ TOKEN(AND); }
            YY_BREAK
          case 44: // rule scan-wolf.ll:185: "||" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:185\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 185 "scan-wolf.ll"
{ TOKEN(OR); }
            YY_BREAK
          case 45: // rule scan-wolf.ll:186: ">=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:186\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 186 "scan-wolf.ll"
{ TOKEN(GE); }
            YY_BREAK
          case 46: // rule scan-wolf.ll:187: "<=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:187\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 187 "scan-wolf.ll"
{ TOKEN(LE); }
            YY_BREAK
          case 47: // rule scan-wolf.ll:188: ">" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:188\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 188 "scan-wolf.ll"
{ TOKEN(GT); }
            YY_BREAK
          case 48: // rule scan-wolf.ll:189: "<" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:189\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 189 "scan-wolf.ll"
{ TOKEN(LT); }
            YY_BREAK
          case 49: // rule scan-wolf.ll:190: "!" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:190\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 190 "scan-wolf.ll"
{ TOKEN(NOT); }
            YY_BREAK
          case 50: // rule scan-wolf.ll:191: "+" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:191\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 191 "scan-wolf.ll"
{ TOKEN(PLUS); }
            YY_BREAK
          case 51: // rule scan-wolf.ll:192: "-" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:192\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 192 "scan-wolf.ll"
{ TOKEN(MINUS); }
            YY_BREAK
          case 52: // rule scan-wolf.ll:193: "*" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:193\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 193 "scan-wolf.ll"
{ TOKEN(STAR); }
            YY_BREAK
          case 53: // rule scan-wolf.ll:194: "/" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:194\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 194 "scan-wolf.ll"
{ TOKEN(DIV); }
            YY_BREAK
          case 54: // rule scan-wolf.ll:195: "%" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:195\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 195 "scan-wolf.ll"
{ TOKEN(MOD); }
            YY_BREAK
          case 55: // rule scan-wolf.ll:196: "~" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:196\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 196 "scan-wolf.ll"
{ TOKEN(TILD); }
            YY_BREAK
          case 56: // rule scan-wolf.ll:197: "&" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:197\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 197 "scan-wolf.ll"
{ TOKEN(AMP); }
            YY_BREAK
          case 57: // rule scan-wolf.ll:198: "|" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:198\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 198 "scan-wolf.ll"
{ TOKEN(PIPE); }
            YY_BREAK
          case 58: // rule scan-wolf.ll:199: "^" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:199\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 199 "scan-wolf.ll"
{ TOKEN(XOR); }
            YY_BREAK
          case 59: // rule scan-wolf.ll:200: ">>" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:200\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 200 "scan-wolf.ll"
{ TOKEN(RSHIFT); }
            YY_BREAK
          case 60: // rule scan-wolf.ll:201: "<<" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:201\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 201 "scan-wolf.ll"
{ TOKEN(LSHIFT); }
            YY_BREAK
          case 61: // rule scan-wolf.ll:202: "?" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:202\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 202 "scan-wolf.ll"
{ TOKEN(QUESTION); }

            YY_BREAK
          case 62: // rule scan-wolf.ll:204: "++" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:204\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 204 "scan-wolf.ll"
{ TOKEN(INC); }
            YY_BREAK
          case 63: // rule scan-wolf.ll:205: "--" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:205\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 205 "scan-wolf.ll"
{ TOKEN(DEC); }

            YY_BREAK
          case 64: // rule scan-wolf.ll:207: "+=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:207\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 207 "scan-wolf.ll"
{ TOKEN(PLUS_ASSIGN); }
            YY_BREAK
          case 65: // rule scan-wolf.ll:208: "-=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:208\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 208 "scan-wolf.ll"
{ TOKEN(MINUS_ASSIGN); }
            YY_BREAK
          case 66: // rule scan-wolf.ll:209: "*=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:209\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 209 "scan-wolf.ll"
{ TOKEN(MULT_ASSIGN); }
            YY_BREAK
          case 67: // rule scan-wolf.ll:210: "/=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:210\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 210 "scan-wolf.ll"
{ TOKEN(DIV_ASSIGN); }
            YY_BREAK
          case 68: // rule scan-wolf.ll:211: "%=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:211\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 211 "scan-wolf.ll"
{ TOKEN(MOD_ASSIGN); }
            YY_BREAK
          case 69: // rule scan-wolf.ll:212: "&=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:212\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 212 "scan-wolf.ll"
{ TOKEN(AMP_ASSIGN); }
            YY_BREAK
          case 70: // rule scan-wolf.ll:213: "|=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:213\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 213 "scan-wolf.ll"
{ TOKEN(PIPE_ASSIGN); }
            YY_BREAK
          case 71: // rule scan-wolf.ll:214: "^=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:214\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 214 "scan-wolf.ll"
{ TOKEN(XOR_ASSIGN); }
            YY_BREAK
          case 72: // rule scan-wolf.ll:215: ">>=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:215\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 215 "scan-wolf.ll"
{ TOKEN(RSHIFT_ASSIGN); }
            YY_BREAK
          case 73: // rule scan-wolf.ll:216: "<<=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:216\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 216 "scan-wolf.ll"
{ TOKEN(LSHIFT_ASSIGN); }

            YY_BREAK
          case 74: // rule scan-wolf.ll:218: "=" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:218\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 218 "scan-wolf.ll"
{ TOKEN(ASSIGN); }
            YY_BREAK
          case 75: // rule scan-wolf.ll:219: "." :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:219\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 219 "scan-wolf.ll"
{ TOKEN(DOT); }
            YY_BREAK
          case 76: // rule scan-wolf.ll:220: "->" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:220\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 220 "scan-wolf.ll"
{ TOKEN(ARROW); }
            YY_BREAK
          case 77: // rule scan-wolf.ll:221: "," :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:221\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 221 "scan-wolf.ll"
{ TOKEN(COMMA); }
            YY_BREAK
          case 78: // rule scan-wolf.ll:222: ";" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:222\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 222 "scan-wolf.ll"
{ TOKEN(SEMICOLON); }
            YY_BREAK
          case 79: // rule scan-wolf.ll:223: ":" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:223\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 223 "scan-wolf.ll"
{ TOKEN(COLON); }
            YY_BREAK
          case 80: // rule scan-wolf.ll:224: "..." :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:224\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 224 "scan-wolf.ll"
{ TOKEN(ELLIPSIS); }

            YY_BREAK
          case 81: // rule scan-wolf.ll:226: "(" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:226\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 226 "scan-wolf.ll"
{ TOKEN(OPAR); }
            YY_BREAK
          case 82: // rule scan-wolf.ll:227: ")" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:227\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 227 "scan-wolf.ll"
{ TOKEN(CPAR); }
            YY_BREAK
          case 83: // rule scan-wolf.ll:228: "{"|"<%" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:228\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 228 "scan-wolf.ll"
{ TOKEN(OCURL); }
            YY_BREAK
          case 84: // rule scan-wolf.ll:229: "}"|"%>" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:229\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 229 "scan-wolf.ll"
{ TOKEN(CCURL); }
            YY_BREAK
          case 85: // rule scan-wolf.ll:230: "["|"<:" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:230\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 230 "scan-wolf.ll"
{ TOKEN(OBRA); }
            YY_BREAK
          case 86: // rule scan-wolf.ll:231: "]"|":>" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:231\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 231 "scan-wolf.ll"
{ TOKEN(CBRA); }

            YY_BREAK
          case 87: // rule scan-wolf.ll:233: {number} :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:233\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 233 "scan-wolf.ll"
{ TOKEN_VAL(NUM, text()); }
            YY_BREAK
          case 88: // rule scan-wolf.ll:234: {STRING_LITERAL} :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:234\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 234 "scan-wolf.ll"
{ TOKEN_VAL(STRING, text()); }
            YY_BREAK
          case 89: // rule scan-wolf.ll:235: {ID} :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:235\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 235 "scan-wolf.ll"
{ TOKEN_VAL(IDENTIFIER, text()); }

            YY_BREAK
          case 90: // rule scan-wolf.ll:239: . :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:239\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 239 "scan-wolf.ll"
{
	(void)tokens;
	wd.error_get() << "Invalid character: " << yytext[0] << "\n";
}

            YY_BREAK
        }
        break;
      case SC_COMMENT:
        matcher().pattern(PATTERN_SC_COMMENT);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              if (debug()) std::cerr << "--\033[1;35mEOF rule scan-wolf.ll:94\033[0m start(" << start() << ")\n";
#line 94 "scan-wolf.ll"
{
		wd.error_get() << misc::error_type::scan
			<< "Comment never finish at "
			// << td.location_
			<< "\n";
	}

            }
            else
            {
              if (debug()) std::cerr << "--\033[1;31mdefault rule\033[0m\n";
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule scan-wolf.ll:82: "/*" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:82\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 82 "scan-wolf.ll"
{
		lvl++;
	}

            YY_BREAK
          case 2: // rule scan-wolf.ll:86: "*/" :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:86\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 86 "scan-wolf.ll"
{
		lvl--;
		if (lvl == 0)
		{
			start(INITIAL);
		}
	}

            YY_BREAK
          case 3: // rule scan-wolf.ll:101: .|\n :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:101\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 101 "scan-wolf.ll"
{}


            YY_BREAK
        }
        break;
      case SC_NEW_LOC:
        matcher().pattern(PATTERN_SC_NEW_LOC);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              if (debug()) std::cerr << "--\033[1;35mEOF rule scan-wolf.ll:237\033[0m start(" << start() << ")\n";
#line 237 "scan-wolf.ll"
{ TOKEN(END_OF_FILE); return 0; }

            }
            else
            {
              if (debug()) std::cerr << "--\033[1;31mdefault rule\033[0m\n";
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule scan-wolf.ll:104: {number} :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:104\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 104 "scan-wolf.ll"
{
	if (new_line  == -1)
	{
		new_line = std::stoi(text());
	}
}

            YY_BREAK
          case 2: // rule scan-wolf.ll:111: {STRING_LITERAL} :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:111\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 111 "scan-wolf.ll"
{
	new_file = text();
	new_file.erase(0, 1);
	new_file.erase(new_file.size() - 1);
}

            YY_BREAK
          case 3: // rule scan-wolf.ll:117: . :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:117\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 117 "scan-wolf.ll"
{}

            YY_BREAK
          case 4: // rule scan-wolf.ll:119: \n :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:119\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 119 "scan-wolf.ll"
{
	// std::cout << "New Loc: " << new_file<< ":" << new_line << "\n";

	file = new_file;
	col = 0;
	line = new_line;

	start(INITIAL);
}


            YY_BREAK
        }
        break;
      default:
        start(0);
    }
  }
}
