// scan-wolf.cc generated by reflex 3.3.0 from scan-wolf.ll

#define REFLEX_VERSION "3.3.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_debug
#undef REFLEX_OPTION_flex
#undef REFLEX_OPTION_header_file
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_noyywrap
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_params
#undef REFLEX_OPTION_prefix

#define REFLEX_OPTION_debug               true
#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_header_file         "scan-wolf.hh"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           lexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "scan-wolf.cc"
#define REFLEX_OPTION_params              driver::WolfDriver& wd, std::vector<lexer::Token>& tokens
#define REFLEX_OPTION_prefix              yy

// --debug option enables ASSERT:
#define ASSERT(c) assert(c)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 12 "scan-wolf.ll"


#define YY_EXTERN_C extern "C" // For linkage rule

#include <cerrno>
#include <climits>
#include <regex>
#include <string>

#include "token.hh"
#include "../driver/wolf-driver.hh"

	/* (Define YY_USER_ACTION to update locations). */
// TODO #define YY_USER_ACTION td.location_ += size();


#define TOKEN(Type)                             \
  lexer::make_ ## Type(td.location_)

#define TOKEN_VAL(Type, Value)                  \
  lexer::make_ ## Type(Value, td.location_)




////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE DEFINITIONS                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define INITIAL (0)
#define YY_NUM_RULES (1)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>

namespace lexer {

typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;

} // namespace lexer

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace lexer {

class Lexer : public FlexLexer {
#line 38 "scan-wolf.ll"

	unsigned line;
	unsigned col;

 public:
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
#line 43 "scan-wolf.ll"

	line = 0;
	col = 0;

    set_debug(true);
  }
  virtual int yylex(void)
  {
    LexerError("Lexer::yylex invoked but %option lex=lex is used");
    yyterminate();
  }
  // the flex lexer function defined by SECTION 2
  virtual int lex(driver::WolfDriver& wd, std::vector<lexer::Token>& tokens);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input, driver::WolfDriver& wd, std::vector<lexer::Token>& tokens)
  {
    in(input);
    return lex(wd, tokens);
  }
  int lex(const reflex::Input& input, std::ostream *os, driver::WolfDriver& wd, std::vector<lexer::Token>& tokens)
  {
    in(input);
    if (os)
      out(*os);
    return lex(wd, tokens);
  }
};

} // namespace lexer

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "scan-wolf.ll"
/* -*- C++ -*- */
// %option defines the parameters with which the flex will be launched
#line 6 "scan-wolf.ll"
// Add a param of function lex() generate in Lexer class
#line 9 "scan-wolf.ll"
// Name of the class generate by flex
#line 48 "scan-wolf.ll"
/* Abbreviations.  */

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int lexer::Lexer::lex(driver::WolfDriver& wd, std::vector<lexer::Token>& tokens)
{
  static const char *REGEX_INITIAL = "(?m)(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              if (debug()) std::cerr << "--\033[1;35mEOF\033[0m start(" << start() << ")\n";
              yyterminate();
            }
            else
            {
              if (debug()) std::cerr << "--\033[1;31mdefault rule\033[0m\n";
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule scan-wolf.ll:57: . :
            if (debug()) std::cerr << "--\033[1;35mrule scan-wolf.ll:57\033[0m start(" << start() << ") " << matcher().lineno() << "," << matcher().columno() << ":\"\033[1m" << matcher().text() << "\033[0m\"\n";
            YY_USER_ACTION
#line 57 "scan-wolf.ll"
{
	(void)tokens;
	wd.error_get() << "Invalid character: " << yytext[0] << "\n";
	std::cout << yytext[0] << "\n";
}

            YY_BREAK
        }
  }
}
