// scan-wolf.hh generated by reflex 3.3.0 from scan-wolf.ll

#ifndef REFLEX_SCAN_WOLF_HH
#define REFLEX_SCAN_WOLF_HH
#define yyIN_HEADER 1
#define REFLEX_VERSION "3.3.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_debug
#undef REFLEX_OPTION_flex
#undef REFLEX_OPTION_header_file
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_noyywrap
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_params
#undef REFLEX_OPTION_prefix

#define REFLEX_OPTION_debug               true
#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_header_file         "scan-wolf.hh"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           lexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "scan-wolf.cc"
#define REFLEX_OPTION_params              driver::WolfDriver& wd, std::queue<lexer::Token>& tokens
#define REFLEX_OPTION_prefix              yy

// --debug option enables ASSERT:
#define ASSERT(c) assert(c)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 12 "scan-wolf.ll"


#define YY_EXTERN_C extern "C" // For linkage rule

#include <queue>
#include <cerrno>
#include <climits>
#include <regex>
#include <string>

#include "token.hh"
#include "../driver/wolf-driver.hh"
#include "../misc/location.hh"

	/* (Define YY_USER_ACTION to update locations). */
#define YY_USER_ACTION col += size();

#define GET_LOC Location{file, line, col, col + yyleng - 1}
#define GET_TOK(Type) Type ## _TOK

#define TOKEN(Type)										\
	token_type type = Type ## _TOK;						\
	misc::Location location{file, line, col - YYLeng() + 1, col};	\
	Token token{type, location};						\
	tokens.emplace(token);

#define TOKEN_VAL(Type, Value)										\
	token_type type = Type ## _TOK;									\
	misc::Location location{file, line, col - YYLeng() + 1, col};	\
	Token token{type, location, Value};						\
	tokens.emplace(token);




////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>

namespace lexer {

typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;

} // namespace lexer

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace lexer {

class Lexer : public FlexLexer {
#line 48 "scan-wolf.ll"

	std::string file;
	unsigned line;
	unsigned col;

	// Use to got new location
	std::string new_file;
	int new_line;

	// Use to detect subcomment
	unsigned lvl;

 public:
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
#line 61 "scan-wolf.ll"

	file = "";
	line = 0;
	col = 0;

	new_file = "";
	new_line = 0;

	lvl = 0;

    set_debug(true);
  }
  virtual int yylex(void)
  {
    LexerError("Lexer::yylex invoked but %option lex=lex is used");
    yyterminate();
  }
  // the flex lexer function defined by SECTION 2
  virtual int lex(driver::WolfDriver& wd, std::queue<lexer::Token>& tokens);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input, driver::WolfDriver& wd, std::queue<lexer::Token>& tokens)
  {
    in(input);
    return lex(wd, tokens);
  }
  int lex(const reflex::Input& input, std::ostream *os, driver::WolfDriver& wd, std::queue<lexer::Token>& tokens)
  {
    in(input);
    if (os)
      out(*os);
    return lex(wd, tokens);
  }
};

} // namespace lexer

#endif
